version: '3'
services:
  app:
    build: .
    networks:
      - robottestsnw
    volumes:
      - .:/usr/app/
      - shared:/shared-data
    ports:
      - "3000:3000"
    depends_on:
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - BROWSER=firefox

  selenium_hub:
    image: selenium/hub:4.15.0-20231108
    container_name: selenium_hub
    volumes:
      - shared:/shared-data
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - robottestsnw

  firefox:
    image: selenium/node-firefox:4.15.0-20231108
    shm_size: 2gb
    volumes:
      - shared:/shared-data
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - robottestsnw 

networks:
  robottestsnw:
    driver: bridge

volumes:
  shared:   