version: '3'
services:
  app:
    build: .
    networks:
      robottestsnw: {}
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - selenium_hub
      - firefox
    environment:
        - HUB_HOST=selenium-hub
        - BROWSER=firefox

  selenium_hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium_hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      robottestsnw: {}

  firefox:
    image: selenium/node-firefox:4.7.2-20221219
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      robottestsnw: {} 

networks:
  robottestsnw:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112
